"""
Project-specific report figures, computed from the real recorded sessions.

full_model_report.py already produces the ~20 standard classifier diagnostics
(confusion matrices, ROC/PR, learning and validation curves, feature
importance). This script produces the figures that are specific to THIS
project's findings and that a generic classifier report cannot know to draw:

    21  waterfall, empty vs moving          the raw signal, side by side
    22  motion energy across a transition   what the model actually keys on
    23  class separation, quiet vs loud     WHY a loud room is hard
    24  noise floor per session             the environment, graded
    25  noise floor vs held-out accuracy    the project's signature finding
    26  feature importance by family        which of the 5 families carries it

Nothing here is hand-typed: every number is recomputed from the session CSVs,
the saved model, or per_fold_results.csv as written by full_model_report.py.
Figures 25 needs those fold results, so run that script first:

    python full_model_report.py --model csi_model.joblib --sessions <all ten>
    python make_report_figures.py

Output: 300 dpi PNGs, sized for a single column of an A4 report.
"""

import argparse
import os
import sys

import joblib
import numpy as np
import pandas as pd

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from matplotlib.backends.backend_pdf import PdfPages
from matplotlib.colors import LinearSegmentedColormap

from csi_common import (NOISE_REL_LOUD, NOISE_REL_QUIET, assess_noise_floor,
                         feature_names)
from train_model import DEFAULT_SESSIONS, amp_columns, load_session

# The dashboard's own intensity ramp, so the figures in the report and the
# live interface show the signal in the same colours.
CSI_CMAP = LinearSegmentedColormap.from_list(
    "csi", ["#06101e", "#17588f", "#6fd3f2"])

# Semantic colours, matching the rest of the project: green is a healthy or
# empty state, red is motion or a fault, amber is transitional, blue is data.
C_EMPTY, C_MOVING = "#157f3d", "#c2352f"
C_ACCENT, C_WARN = "#0f62d0", "#a2680b"
C_GRID = "#d8d8d4"

DPI = 300


def style():
    plt.rcParams.update({
        "figure.dpi": 110,
        "savefig.dpi": DPI,
        "font.size": 9,
        "axes.titlesize": 10,
        "axes.labelsize": 9,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "axes.edgecolor": "#8b8e95",
        "axes.grid": True,
        "grid.color": C_GRID,
        "grid.linewidth": 0.6,
        "legend.frameon": False,
        "figure.facecolor": "white",
    })


# Set by main() while a PdfPages is open. Held at module level rather than
# threaded through all six figure functions, which would add a parameter to
# each purely so that save() can reach it.
_PDF = None


def save(fig, out_dir, name):
    """Write the figure as a 300 dpi PNG and, if a PDF is open, add it as a
    page there too. The page is written from the live figure rather than by
    re-importing the PNG, so text and axes stay vector."""
    path = os.path.join(out_dir, name)
    fig.savefig(path, dpi=DPI, bbox_inches="tight", facecolor="white")
    if _PDF is not None:
        _PDF.savefig(fig, bbox_inches="tight", facecolor="white")
    plt.close(fig)
    print("  wrote", path)
    return path


def pdf_title_page(pdf, sessions, model_path):
    """A cover page, so the PDF stands on its own if it is handed to someone."""
    bundle = joblib.load(model_path)
    fig = plt.figure(figsize=(8.27, 11.69))          # A4 portrait
    fig.text(0.5, 0.74, "Wi-Fi CSI Motion Detection", ha="center",
             fontsize=22, fontweight="bold")
    fig.text(0.5, 0.695, "Project-specific result figures", ha="center",
             fontsize=13, color="#55585f")
    fig.text(0.5, 0.655, "generated by make_report_figures.py",
             ha="center", fontsize=9, color="#8b8e95", style="italic")

    lines = [
        f"Model            {os.path.basename(model_path)}",
        f"Classifier       Random Forest, {bundle['model'].n_estimators} trees",
        f"Subcarriers      {len(bundle['amp_columns'])}",
        f"Features         {len(bundle['feature_names'])}",
        f"Window           {bundle['window_seconds']} s "
        f"({max(1, round(bundle['window_seconds'] * bundle['frame_hz']))} frames "
        f"@ {bundle['frame_hz']:.0f} Hz)",
        f"Calibration      {bundle['calib_seconds']} s per empty block",
        f"Sessions         {len(sessions)}",
        "",
        "Every figure is recomputed from the recorded session data;",
        "no value in this document is hand-entered.",
    ]
    fig.text(0.5, 0.52, "\n".join(lines), ha="center", va="top",
             fontsize=10, family="monospace", linespacing=1.75)
    fig.text(0.5, 0.06, pd.Timestamp.now().strftime("%Y-%m-%d %H:%M"),
             ha="center", fontsize=8, color="#8b8e95")
    pdf.savefig(fig, facecolor="white")
    plt.close(fig)


def build_combined_pdf(fig_dir, out_path):
    """Assemble every numbered PNG in `fig_dir` into one A4 figure book.

    Titles are derived from the file names rather than kept in a lookup table,
    so this cannot fall out of step with whatever full_model_report.py happens
    to emit."""
    names = sorted(f for f in os.listdir(fig_dir)
                   if f.lower().endswith(".png") and f[:2].isdigit())
    if not names:
        print("  no PNGs found; skipping combined PDF")
        return None

    with PdfPages(out_path) as pdf:
        fig = plt.figure(figsize=(8.27, 11.69))
        fig.text(0.5, 0.62, "Wi-Fi CSI Motion Detection", ha="center",
                 fontsize=22, fontweight="bold")
        fig.text(0.5, 0.575, "Complete figure set", ha="center",
                 fontsize=13, color="#55585f")
        fig.text(0.5, 0.53, f"{len(names)} figures", ha="center",
                 fontsize=10, color="#8b8e95")
        pdf.savefig(fig, facecolor="white")
        plt.close(fig)

        for n in names:
            num, _, rest = n[:-4].partition("_")
            title = f"{num}.  {rest.replace('_', ' ').capitalize()}"
            img = mpimg.imread(os.path.join(fig_dir, n))
            h, w = img.shape[0], img.shape[1]

            fig = plt.figure(figsize=(8.27, 11.69))
            # Fit the image inside the printable area while preserving aspect.
            avail_w, avail_h = 0.86, 0.78
            scale = min(avail_w / 1.0, avail_h / (h / w) if w else avail_h)
            iw, ih = scale, scale * (h / w)
            ax = fig.add_axes([(1 - iw) / 2, 0.10, iw, ih])
            ax.imshow(img)
            ax.axis("off")
            fig.text(0.5, 0.93, title, ha="center", fontsize=13,
                     fontweight="bold")
            pdf.savefig(fig, facecolor="white")
            plt.close(fig)

    print("  wrote", out_path, f"({len(names)} figures)")
    return out_path


# --------------------------------------------------------------------------
# shared loading helpers
# --------------------------------------------------------------------------
def session_arrays(folder):
    """Return (amps, labels, active_idx) for one session, settling dropped."""
    df = load_session(folder)
    cols = amp_columns(df)
    amps = df[cols].to_numpy(dtype=float)
    labels = df["label"].to_numpy()
    # The ~20 structurally dead guard-band subcarriers sit at exactly zero for
    # the whole recording. They are excluded from every figure: they would draw
    # as a permanent black stripe and would deflate any amplitude average.
    active = np.where(amps.mean(axis=0) > 0)[0]
    return amps, labels, active


def frame_energy(amps):
    """Mean absolute frame-to-frame amplitude change; length len(amps)-1."""
    return np.abs(np.diff(amps, axis=0)).mean(axis=1)


def noise_floor(amps, labels):
    """Scale-free empty-room noise floor, as csi_common defines it: jitter as a
    fraction of received amplitude, over active subcarriers only."""
    e = frame_energy(amps)
    lab = labels[1:]
    empty_e = e[lab == 0].mean() if (lab == 0).any() else np.nan
    empty_cols = amps[labels == 0].mean(axis=0)
    scale = empty_cols[empty_cols > 0].mean() if (empty_cols > 0).any() else np.nan
    return empty_e / scale if scale else np.nan


def short_name(session):
    """part_3_data -> P3, room2_part_1_data -> R2-1. Built from the trailing
    index rather than by string replacement, which previously turned
    room2_part_1_data into the malformed 'R2-_1'."""
    stem = session.replace("_data", "")
    idx = stem.rsplit("_", 1)[-1]
    return f"R2-{idx}" if stem.startswith("room2") else f"P{idx}"


def longest_block(labels, value):
    """Index range of the longest contiguous run of `value`."""
    best = (0, 0)
    start = None
    for i, v in enumerate(labels):
        if v == value and start is None:
            start = i
        elif v != value and start is not None:
            if i - start > best[1] - best[0]:
                best = (start, i)
            start = None
    if start is not None and len(labels) - start > best[1] - best[0]:
        best = (start, len(labels))
    return best


# --------------------------------------------------------------------------
# 21 - waterfall, empty vs moving
# --------------------------------------------------------------------------
def fig_waterfall(out_dir, session, n_frames=150):
    amps, labels, active = session_arrays(session)
    e_lo, e_hi = longest_block(labels, 0)
    m_lo, m_hi = longest_block(labels, 2)

    empty = amps[e_lo:e_lo + n_frames][:, active]
    moving = amps[m_lo:m_lo + n_frames][:, active]
    n = min(len(empty), len(moving))
    empty, moving = empty[:n], moving[:n]

    # One shared colour scale, or the two panels would not be comparable -
    # which is the entire point of the figure.
    both = np.concatenate([empty, moving])
    vmin, vmax = np.percentile(both, 2), np.percentile(both, 98)

    fig, axes = plt.subplots(1, 2, figsize=(7.2, 3.4), sharey=True)
    for ax, data, title, colour in (
            (axes[0], empty, "Room empty", C_EMPTY),
            (axes[1], moving, "Person moving", C_MOVING)):
        im = ax.imshow(data, aspect="auto", origin="upper", cmap=CSI_CMAP,
                       vmin=vmin, vmax=vmax, interpolation="nearest")
        ax.set_title(title, color=colour, fontweight="bold", pad=7)
        ax.set_xlabel("active subcarrier index")
        ax.grid(False)
    axes[0].set_ylabel("time (frames, newest at bottom)")

    cb = fig.colorbar(im, ax=axes, fraction=0.035, pad=0.02)
    cb.set_label("CSI amplitude", fontsize=8)
    cb.ax.tick_params(labelsize=7)

    fig.suptitle(f"Raw CSI amplitude over time  ({session}, {n} frames each)",
                 fontsize=10, y=1.01)
    return save(fig, out_dir, "21_waterfall_empty_vs_moving.png")


# --------------------------------------------------------------------------
# 22 - motion energy across a real empty -> moving transition
# --------------------------------------------------------------------------
def fig_energy_transition(out_dir, session):
    amps, labels, _ = session_arrays(session)
    e = frame_energy(amps)
    lab = labels[1:]

    fig, ax = plt.subplots(figsize=(7.2, 2.9))
    t = np.arange(len(e)) / 10.0  # 10 frames per second

    # Shade the ground-truth blocks, so the reader can see that the trace
    # changes at the labelled boundaries rather than being told that it does.
    start, cur = 0, lab[0]
    for i in range(1, len(lab) + 1):
        if i == len(lab) or lab[i] != cur:
            ax.axvspan(t[start], t[i - 1],
                       color=C_MOVING if cur == 2 else C_EMPTY,
                       alpha=0.10, linewidth=0)
            if i < len(lab):
                start, cur = i, lab[i]
    ax.plot(t, e, color=C_ACCENT, linewidth=0.9)

    ax.set_xlabel("time (s)")
    ax.set_ylabel("motion energy\n(mean |$\\Delta$ amplitude| per frame)")
    ax.set_xlim(t[0], t[-1])
    ax.set_ylim(bottom=0)
    ax.set_title(f"Motion energy across the labelled blocks of {session}",
                 pad=7)

    handles = [plt.Rectangle((0, 0), 1, 1, color=C_EMPTY, alpha=0.25),
               plt.Rectangle((0, 0), 1, 1, color=C_MOVING, alpha=0.25)]
    # Upper LEFT: the empty block sits near zero, so that corner is the only
    # part of the plot guaranteed to be free of data.
    ax.legend(handles, ["labelled EMPTY", "labelled MOVING"],
              loc="upper left", fontsize=8, ncol=2)
    return save(fig, out_dir, "22_motion_energy_transition.png")


# --------------------------------------------------------------------------
# 23 - class separation in a quiet room vs a loud one
# --------------------------------------------------------------------------
def fig_separation(out_dir, quiet_session, loud_session):
    fig, axes = plt.subplots(1, 2, figsize=(7.2, 3.0), sharey=True)

    for ax, session in ((axes[0], quiet_session), (axes[1], loud_session)):
        amps, labels, _ = session_arrays(session)
        e = frame_energy(amps)
        lab = labels[1:]
        emp, mov = e[lab == 0], e[lab == 2]
        n = noise_floor(amps, labels)
        level, _, _ = assess_noise_floor(n)
        sep = mov.mean() / emp.mean()

        bins = np.linspace(0, np.percentile(e, 99.5), 55)
        ax.hist(emp, bins=bins, color=C_EMPTY, alpha=0.55, label="empty", density=True)
        ax.hist(mov, bins=bins, color=C_MOVING, alpha=0.55, label="moving", density=True)
        ax.axvline(emp.mean(), color=C_EMPTY, linestyle="--", linewidth=1.2)
        ax.axvline(mov.mean(), color=C_MOVING, linestyle="--", linewidth=1.2)
        ax.set_title(f"{session}\nnoise floor {n:.3f} ({level}),  "
                     f"separation {sep:.2f}$\\times$", fontsize=9, pad=7)
        ax.set_xlabel("motion energy per frame")
    axes[0].set_ylabel("density")
    axes[0].legend(fontsize=8)

    fig.suptitle("Why a loud room is hard: the two classes stop being separable",
                 fontsize=10, y=1.03)
    return save(fig, out_dir, "23_class_separation_quiet_vs_loud.png")


# --------------------------------------------------------------------------
# 24 - noise floor per session
# --------------------------------------------------------------------------
def fig_noise_per_session(out_dir, sessions):
    rows = []
    for s in sessions:
        amps, labels, _ = session_arrays(s)
        n = noise_floor(amps, labels)
        level, _, _ = assess_noise_floor(n)
        rows.append((s, n, level))
    rows.sort(key=lambda r: r[1])

    names = [short_name(r[0]) for r in rows]
    vals = [r[1] for r in rows]
    cols = {"quiet": C_EMPTY, "moderate": C_WARN, "loud": C_MOVING}
    bars = [cols[r[2]] for r in rows]

    fig, ax = plt.subplots(figsize=(7.2, 3.0))
    ax.bar(names, vals, color=bars, width=0.62)
    ax.axhline(NOISE_REL_QUIET, color=C_EMPTY, linestyle="--", linewidth=1)
    ax.axhline(NOISE_REL_LOUD, color=C_MOVING, linestyle="--", linewidth=1)
    # Anchored at the LEFT, where the bars are shortest, so the threshold
    # captions cannot land on top of the tall loud-session bars.
    ax.text(-0.45, NOISE_REL_QUIET + 0.005, f"quiet threshold {NOISE_REL_QUIET}",
            va="bottom", ha="left", fontsize=7.5, color=C_EMPTY)
    ax.text(-0.45, NOISE_REL_LOUD + 0.005, f"loud threshold {NOISE_REL_LOUD}",
            va="bottom", ha="left", fontsize=7.5, color=C_MOVING)
    for i, v in enumerate(vals):
        ax.text(i, v + 0.004, f"{v:.3f}", ha="center", fontsize=7)

    ax.set_ylabel("empty-room noise floor\n(jitter / mean amplitude)")
    ax.set_title("Measured noise floor of every recording session", pad=7)
    ax.set_ylim(0, max(vals) * 1.18)
    ax.set_xlim(-0.6, len(names) - 0.4)
    ax.tick_params(axis="x", labelsize=8)
    return save(fig, out_dir, "24_noise_floor_per_session.png")


# --------------------------------------------------------------------------
# 25 - noise floor vs held-out accuracy
# --------------------------------------------------------------------------
def fig_noise_vs_accuracy(out_dir, sessions, fold_csv):
    if not os.path.exists(fold_csv):
        print(f"  SKIPPED 25: {fold_csv} not found. Run full_model_report.py first.")
        return None
    folds = pd.read_csv(fold_csv).set_index("held_out_session")["test_accuracy"]

    xs, ys, names, cols = [], [], [], []
    for s in sessions:
        if s not in folds.index:
            continue
        amps, labels, _ = session_arrays(s)
        n = noise_floor(amps, labels)
        level, _, _ = assess_noise_floor(n)
        xs.append(n)
        ys.append(folds[s] * 100)
        names.append(s.replace("_data", ""))
        cols.append({"quiet": C_EMPTY, "moderate": C_WARN, "loud": C_MOVING}[level])

    fig, ax = plt.subplots(figsize=(7.2, 3.6))
    ax.axvspan(0, NOISE_REL_QUIET, color=C_EMPTY, alpha=0.06)
    ax.axvspan(NOISE_REL_QUIET, NOISE_REL_LOUD, color=C_WARN, alpha=0.06)
    ax.axvspan(NOISE_REL_LOUD, max(xs) * 1.14, color=C_MOVING, alpha=0.06)
    ax.scatter(xs, ys, c=cols, s=46, zorder=3, edgecolor="white", linewidth=0.8)

    # Place each label clear of its neighbours. With ten sessions and several
    # near-identical noise floors, a fixed offset overlaps: part_2 and part_3
    # printed on top of each other before this.
    order = np.argsort(xs)
    placed = []
    for i in order:
        x, y = xs[i], ys[i]
        for dx, dy, ha in ((7, -3, "left"), (7, 5, "left"), (-7, -3, "right"),
                           (7, -11, "left"), (-7, 5, "right")):
            # reject an offset whose anchor sits close to one already used
            cand = (x + dx * 0.0006, y + dy * 0.12)
            if all(abs(cand[0] - p[0]) > 0.008 or abs(cand[1] - p[1]) > 0.9
                   for p in placed):
                break
        placed.append(cand)
        ax.annotate(names[i], (x, y), textcoords="offset points",
                    xytext=(dx, dy), ha=ha, fontsize=7, color="#55585f")

    ax.set_xlabel("empty-room noise floor")
    ax.set_ylabel("held-out accuracy (%)")
    ax.set_xlim(0, max(xs) * 1.14)
    ax.set_ylim(min(ys) - 3.2, max(ys) + 1.6)
    ax.set_title("Held-out accuracy against measured noise floor", pad=7)

    # The honest caption is the point of this figure: the two loudest sessions
    # differ by ten points, so the floor is a risk indicator, not a forecast.
    # Anchored bottom-LEFT, which is empty - the low-accuracy points are all on
    # the right, where this text used to collide with them.
    r = np.corrcoef(xs, ys)[0, 1]
    ax.text(0.015, 0.04, f"Pearson r = {r:.2f}   (n = {len(xs)})",
            transform=ax.transAxes, ha="left", fontsize=8, color="#55585f")
    return save(fig, out_dir, "25_noise_floor_vs_accuracy.png")


# --------------------------------------------------------------------------
# 27 - what an EMPTY room actually looks like, quiet vs loud
# --------------------------------------------------------------------------
def fig_empty_room_character(out_dir, quiet_session, loud_session):
    """Only the empty-labelled frames, concatenated.

    Figure 23 shows the two classes overlapping in a loud session but not why.
    The reason is visible only in time order: the loud sessions are not
    uniformly noisy, they alternate between a quiet state and a disturbed one.
    That distinction matters, because the noise-floor metric averages, and an
    average over a bursty signal describes neither state.
    """
    fig, axes = plt.subplots(2, 1, figsize=(7.2, 4.6), sharey=True)

    for ax, session, tag in ((axes[0], quiet_session, "quiet"),
                             (axes[1], loud_session, "loud")):
        amps, labels, _ = session_arrays(session)
        e = frame_energy(amps)
        emp = e[labels[1:] == 0]
        t = np.arange(len(emp)) / 10.0

        ax.plot(t, emp, color=C_ACCENT, linewidth=0.55)
        ax.axhline(emp.mean(), color=C_MOVING, linestyle="--", linewidth=1.1)
        ax.axhline(np.median(emp), color=C_EMPTY, linestyle="--", linewidth=1.1)
        ax.set_xlim(0, t[-1])
        ax.set_ylabel("motion energy")
        ax.set_title(
            f"{session}  ({tag}):  mean {emp.mean():.2f}   "
            f"median {np.median(emp):.2f}   "
            f"{(emp > 5).mean() * 100:.0f}% of frames above 5",
            fontsize=9, pad=6, loc="left")
    axes[1].set_xlabel("time within the empty blocks (s)")

    handles = [plt.Line2D([], [], color=C_MOVING, linestyle="--"),
               plt.Line2D([], [], color=C_EMPTY, linestyle="--")]
    axes[0].legend(handles, ["mean", "median"], fontsize=8, ncol=2,
                   loc="upper right")

    fig.suptitle("An empty room is not uniformly quiet: the loud sessions burst",
                 fontsize=10, y=0.99)
    fig.tight_layout(rect=(0, 0, 1, 0.96))
    return save(fig, out_dir, "27_empty_room_character.png")


# --------------------------------------------------------------------------
# 26 - feature importance grouped by family
# --------------------------------------------------------------------------
def fig_importance_by_family(out_dir, model_path):
    bundle = joblib.load(model_path)
    imp = bundle["model"].feature_importances_
    names = bundle.get("feature_names") or feature_names(bundle["amp_columns"])
    n_amp = len(bundle["amp_columns"])

    # The five families, in the order calibrate_features concatenates them.
    # Short two-line labels: the full family names ("per-subcarrier mean
    # delta") overran their tick spacing and printed on top of each other.
    groups = [
        ("subcarrier\nmean delta", slice(0, n_amp), n_amp),
        ("subcarrier\nstd ratio", slice(n_amp, 2 * n_amp), n_amp),
        ("motion\nenergy", slice(2 * n_amp, 2 * n_amp + 2), 2),
        ("RSSI", slice(2 * n_amp + 2, 2 * n_amp + 4), 2),
        ("order-\ninvariant", slice(2 * n_amp + 4, len(names)), len(names) - (2 * n_amp + 4)),
    ]

    total = [imp[g[1]].sum() * 100 for g in groups]
    per_feat = [t / g[2] for t, g in zip(total, groups)]
    labels = [g[0] for g in groups]
    counts = [g[2] for g in groups]

    fig, axes = plt.subplots(1, 2, figsize=(7.6, 3.4))
    axes[0].bar(labels, total, color=C_ACCENT, width=0.6)
    axes[0].set_ylabel("total importance (%)")
    axes[0].set_title("Importance summed over each family", fontsize=9, pad=6)
    for i, (v, c) in enumerate(zip(total, counts)):
        axes[0].text(i, v + 0.7, f"{v:.1f}%\n({c} feat.)", ha="center", fontsize=7)
    axes[0].set_ylim(0, max(total) * 1.28)

    axes[1].bar(labels, per_feat, color=C_WARN, width=0.6)
    axes[1].set_ylabel("importance per feature (%)")
    axes[1].set_title("Importance per individual feature", fontsize=9, pad=6)
    for i, v in enumerate(per_feat):
        axes[1].text(i, v + max(per_feat) * 0.03, f"{v:.2f}%", ha="center", fontsize=7)
    axes[1].set_ylim(0, max(per_feat) * 1.25)

    for ax in axes:
        ax.tick_params(axis="x", labelsize=7)

    fig.suptitle("Where the model's discriminative power sits", fontsize=10, y=1.03)
    fig.subplots_adjust(wspace=0.32)
    return save(fig, out_dir, "26_feature_importance_by_family.png")


# --------------------------------------------------------------------------
def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--sessions", nargs="+", default=DEFAULT_SESSIONS)
    ap.add_argument("--model", default="csi_model.joblib")
    ap.add_argument("--out-dir", default=os.path.join("report_output", "figures"))
    ap.add_argument("--fold-results",
                    default=os.path.join("report_output", "per_fold_results.csv"),
                    help="written by full_model_report.py; needed for figure 25")
    ap.add_argument("--waterfall-session", default=None,
                    help="session to draw figures 21/22 from "
                         "(default: the quietest, which shows the signal most clearly)")
    ap.add_argument("--pdf", default=os.path.join("report_output",
                                                   "csi_project_figures.pdf"),
                    help="PDF of the six figures produced here "
                         "(pass an empty string to skip)")
    ap.add_argument("--combined-pdf",
                    default=os.path.join("report_output", "csi_all_figures.pdf"),
                    help="PDF assembling EVERY numbered PNG in --out-dir, i.e. "
                         "these six plus the ~20 from full_model_report.py "
                         "(pass an empty string to skip)")
    args = ap.parse_args()

    global _PDF

    os.makedirs(args.out_dir, exist_ok=True)
    if args.pdf:
        os.makedirs(os.path.dirname(args.pdf) or ".", exist_ok=True)
    style()

    # Pick the quietest and loudest sessions by measurement rather than by
    # hand, so the figures stay correct if the dataset changes.
    floors = {}
    for s in args.sessions:
        amps, labels, _ = session_arrays(s)
        floors[s] = noise_floor(amps, labels)
    quietest = min(floors, key=floors.get)
    loudest = max(floors, key=floors.get)
    print(f"Quietest session: {quietest} ({floors[quietest]:.4f})")
    print(f"Loudest session:  {loudest} ({floors[loudest]:.4f})\n")

    wf = args.waterfall_session or quietest
    print("Generating figures...")

    pdf = PdfPages(args.pdf) if args.pdf else None
    _PDF = pdf
    try:
        if pdf is not None:
            pdf_title_page(pdf, args.sessions, args.model)
        fig_waterfall(args.out_dir, wf)
        fig_energy_transition(args.out_dir, wf)
        fig_separation(args.out_dir, quietest, loudest)
        fig_noise_per_session(args.out_dir, args.sessions)
        fig_noise_vs_accuracy(args.out_dir, args.sessions, args.fold_results)
        fig_importance_by_family(args.out_dir, args.model)
        fig_empty_room_character(args.out_dir, quietest, loudest)
    finally:
        _PDF = None
        if pdf is not None:
            pdf.close()
            print("  wrote", args.pdf)

    if args.combined_pdf:
        print("\nAssembling the complete figure book...")
        os.makedirs(os.path.dirname(args.combined_pdf) or ".", exist_ok=True)
        build_combined_pdf(args.out_dir, args.combined_pdf)

    print("\nDone.")


if __name__ == "__main__":
    main()
